### ISSUE TITLE
Fail to delete deck

### ISSUE THREAD

**Issue by ryuzee** [ryuzee/SlideHub#253]
Failed to delete a deck in Azure Environmnt

**Comment by ryuzee** [comment]
```
bs = ::Azure::Blob::BlobService.new
files.each do |f|
  bs.delete_blob(container, f)
end
```

lib/slide_hub/cloud/engine/azure.rb:133:in `block in delete_files'
lib/slide_hub/cloud/engine/azure.rb:132:in `each'
lib/slide_hub/cloud/engine/azure.rb:132:in `delete_files'
lib/slide_hub/cloud/engine/azure.rb:113:in `delete_slide'
app/controllers/slides_controller.rb:55:in `destroy'
