### ISSUE TITLE
migrateに失敗する

### ISSUE THREAD

**Issue by Zaki-XL** [ryuzee/SlideHub#368]
@ryuzee 
1.6にバージョンアップした所、migrate中のseed処理でabortします

```
[root@ip-xx-xx-xx-xx ~]# docker exec $CONTAINER_ID bash -l -c 'bundle exec rake db:seed RAILS_ENV=production'
stdin: is not a tty
rake aborted!
ActiveModel::UnknownAttributeError: unknown attribute 'name' for Category.
/opt/application/current/vendor/bundle/ruby/2.5.0/gems/activemodel-5.1.6/lib/active_model/attribute_assignment.rb:48:in `_assign_attribute'
/opt/application/current/vendor/bundle/ruby/2.5.0/gems/activemodel-5.1.6/lib/active_model/attribute_assignment.rb:40:in `block in _assign_attributes'
/opt/application/current/vendor/bundle/ruby/2.5.0/gems/activemodel-5.1.6/lib/active_model/attribute_assignment.rb:39:in `each'
/opt/application/current/vendor/bundle/ruby/2.5.0/gems/activemodel-5.1.6/lib/active_model/attribute_assignment.rb:39:in `_assign_attributes'
/opt/application/current/vendor/bundle/ruby/2.5.0/gems/activerecord-5.1.6/lib/active_record/attribute_assignment.rb:26:in `_assign_attributes'
/opt/application/current/vendor/bundle/ruby/2.5.0/gems/activemodel-5.1.6/lib/active_model/attribute_assignment.rb:33:in `assign_attributes'
/opt/application/current/vendor/bundle/ruby/2.5.0/gems/activerecord-5.1.6/lib/active_record/core.rb:337:in `initialize'
/opt/application/current/vendor/bundle/ruby/2.5.0/gems/activerecord-5.1.6/lib/active_record/inheritance.rb:66:in `new'
/opt/application/current/vendor/bundle/ruby/2.5.0/gems/activerecord-5.1.6/lib/active_record/inheritance.rb:66:in `new'
/opt/application/current/vendor/bundle/ruby/2.5.0/gems/activerecord-5.1.6/lib/active_record/persistence.rb:33:in `create'
/opt/application/current/vendor/bundle/ruby/2.5.0/gems/activerecord-5.1.6/lib/active_record/persistence.rb:31:in `block in create'
/opt/application/current/vendor/bundle/ruby/2.5.0/gems/activerecord-5.1.6/lib/active_record/persistence.rb:31:in `collect'
/opt/application/current/vendor/bundle/ruby/2.5.0/gems/activerecord-5.1.6/lib/active_record/persistence.rb:31:in `create'
/opt/application/current/db/seeds.rb:9:in `<top (required)>'
/opt/application/current/vendor/bundle/ruby/2.5.0/gems/activesupport-5.1.6/lib/active_support/dependencies.rb:286:in `load'
/opt/application/current/vendor/bundle/ruby/2.5.0/gems/activesupport-5.1.6/lib/active_support/dependencies.rb:286:in `block in load'
/opt/application/current/vendor/bundle/ruby/2.5.0/gems/activesupport-5.1.6/lib/active_support/dependencies.rb:258:in `load_dependency'
/opt/application/current/vendor/bundle/ruby/2.5.0/gems/activesupport-5.1.6/lib/active_support/dependencies.rb:286:in `load'
/opt/application/current/vendor/bundle/ruby/2.5.0/gems/railties-5.1.6/lib/rails/engine.rb:549:in `load_seed'
/opt/application/current/vendor/bundle/ruby/2.5.0/gems/activerecord-5.1.6/lib/active_record/tasks/database_tasks.rb:270:in `load_seed'
/opt/application/current/vendor/bundle/ruby/2.5.0/gems/activerecord-5.1.6/lib/active_record/railties/databases.rake:184:in `block (2 levels) in <top (required)>'
/opt/application/current/vendor/bundle/ruby/2.5.0/gems/rake-12.3.1/exe/rake:27:in `<top (required)>'
/root/.rbenv/versions/2.5.0/bin/bundle:23:in `load'
/root/.rbenv/versions/2.5.0/bin/bundle:23:in `<main>'
Tasks: TOP => db:seed
(See full trace by running task with --trace)
```

ご確認よろしくお願いいたします

**Comment by Zaki-XL** [comment]
seed処理でabortしてるのでadminでログインできなかった…

**Comment by ryuzee** [comment]
Sorry for the bother. I’ve understood the reason and the defect will be fixed soon. 
If you already have a running application, what only you need to do is to run migration.( do not need to run seed )

**Comment by ryuzee** [comment]
すいません。修正しました。もう一度、`1.6.0`をPullしていただけますか？

**Comment by Zaki-XL** [comment]
動作確認させていただきました
ご対応ありがとうございました
